### ISSUE TITLE
List of modified Kentico files

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#12]
Modifying any of the default Kentico files is not a best practice. We can benefit from a list of all the modified Kentico files and recommend to the customer that this file could be overwritten anytime in next hotfix.

This could be challenging to develop, as in every hotfix some files are changed.

**Comment by petrsvihlik** [comment]
I think this is out of the scope of this project. Hotfix utility provides enough information about changed files based on checksums. There is no way we could achieve this in this utility. Moreover, hotfix doesn't overwrite the files but stores the conflicting files next to the changed ones. I'm closing this issue. Please reopen if you think otherwise.
