### ISSUE TITLE
Workflow Consistency module reporting false-positives in Kentico 10

### ISSUE THREAD

**Issue by kentico-ericd** [Kentico/KInspector#170]
This module is reporting fields are not matching when they are! The page type in the example is Content Only, and the field is integer data type.

Please see attached image for detailed explanation.

![workflowconsistency](https://user-images.githubusercontent.com/25795122/37912877-77b13064-30e1-11e8-8633-ca838a3a5cd3.png)

**Comment by vasila** [comment]
+1

This is due to this line in Kentico.KInspector.Modules.WorkflowConsistencyModule.cs:

`XmlNodeList fields = xml.SelectNodes("/NewDataSet/Table1/*");`

CMS_VersionHistory.NodeXML column no longer contains <Table1> node. Instead, it uses the name of the class DB table as the name of the node, e.g.:

`<NewDataSet>
  <CMS_Root>
    <NodeID>5</NodeID>...`
