### ISSUE TITLE
Migrate "Transformation analyzer" module to V4 report

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/KInspector#243]
### Overview
We should migrate the [Transformation analyzer](https://github.com/Kentico/KInspector/blob/master/KInspector.Modules/Modules/Security/TransformationAnalyzerModule.cs) module to the new V4 report format.

### Definition of done
- [ ] Code and Scripts are ported to `KenticoInspector.Reports` project in a dedicated folder for the report.
- [ ] Scripts are referenced via constants in a static class.
- [ ] Scripts are refactored to return simple results that are mappable to simple classes.
- [ ] Report logic is covered by unit test for a clean result
- [ ] Report logic is covered by unit tests for all known dirty results
- [ ] Useful, non-specific logic is abstracted to services or helpers.

_Note: The [Class/Table Validation report](https://github.com/Kentico/KInspector/tree/v4-dev/KenticoInspector.Reports/ClassTableValidation) (and it's [tests](https://github.com/Kentico/KInspector/blob/v4-dev/KenticoInspector.Reports.Tests/ClassTableValidationTests.cs)) is a good, simple example of the main concepts._

### Additional Details
- New name: __Transformation Security Analysis__
- Tags: __Portal Engine, Security, Transformations__

**Comment by yuriys-kentico** [comment]
I claim ownership!

**Comment by yuriys-kentico** [comment]
I am unsure how to format the results. I have three ideas:

**List of tables by issue type**
Each issue will have a separate table, and each row will be the snippet, reason, property details, web part, and template.

Drawback: Repetition of web part and template details.

**One table by transformation**
Each transformation is a row with the snippets, reason and template usage.

Drawback: Repetition of web part and template details.

**One table by template**
Each template is a "row" with a nested structure for web parts, their properties, and issues under each transformation. It would look like this:

![NestedTable](https://user-images.githubusercontent.com/34716163/60841951-065bd900-a1a1-11e9-91d8-7c70401fd058.png)

Drawback: Not sure how to display that in a plain table. Each cell has text wrapping, so it is impossible to maintain cell divisions. Issue reasons could be duplicated in the last column.

I like the last one because it allows a user to see where in a site an issue appears. This context could help locate the transformation on the page and also affect its severity.
